# Generated by Django 4.2 on 2024-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('numero_habitacion', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
