# Generated by Django 4.2 on 2024-09-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_reserva_creado_en_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_reserva',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Limpieza', 'Limpieza'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=10),
        ),
    ]
