# Generated by Django 4.2 on 2024-09-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_reserva_duracion_reserva_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
