# Generated by Django 4.2 on 2024-09-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Limpieza', 'Limpieza'), ('Disponible', 'Disponible'), ('Cancelada', 'Cancelada')], default='Activa', max_length=10),
        ),
    ]
