# Generated by Django 4.2 on 2024-09-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activa', 'Activa'), ('Limpieza', 'Limpieza'), ('Disponible', 'Disponible'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=10),
        ),
    ]
