# Generated by Django 4.2 on 2024-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ocupada', 'Ocupada'), ('Limpieza', 'Limpieza')], default='Pendiente', max_length=10),
        ),
    ]
