# Generated by Django 4.2 on 2024-09-29 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='gestion.reserva')),
            ],
        ),
    ]
