# Generated by Django 4.2 on 2024-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula_cliente',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horas_extras',
            field=models.IntegerField(default=0),
        ),
    ]
