# Generated by Django 4.2 on 2024-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_reserva_cedula_cliente_reserva_horas_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=4),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
