# Generated by Django 4.2 on 2024-10-01 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_reserva_iva_reserva_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.12'), max_digits=4),
        ),
    ]
