# Generated by Django 4.2 on 2024-10-01 14:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_reserva_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=6),
        ),
    ]
