# Generated by Django 4.2 on 2024-10-01 14:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_reserva_precio_base_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.93'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
    ]
