# Generated by Django 4.2 on 2024-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_reserva_precio_base_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(default='Disponible', max_length=50),
        ),
    ]
