# Generated by Django 4.2 on 2024-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
