# Generated by Django 4.2 on 2024-10-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_habitacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField()),
                ('fecha_inicio_limpieza', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_limpieza', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Limpieza', max_length=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion.reserva')),
            ],
        ),
    ]
