# Generated by Django 4.2 on 2024-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_historiallimpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='historial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistorialLimpieza',
        ),
    ]
