# Generated by Django 4.2 on 2024-10-14 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_reserva_historial_delete_historiallimpieza'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='iva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='iva_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='gestion.iva'),
        ),
    ]
