# Generated by Django 4.2 on 2024-10-28 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_iva_remove_reserva_iva_reserva_iva_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='apellido_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cedula_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.cliente'),
            preserve_default=False,
        ),
    ]
