# Generated by Django 4.2 on 2024-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_cliente_remove_reserva_apellido_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellido_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cedula_cliente',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
