# Generated by Django 4.2 on 2024-10-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_cliente_remove_reserva_apellido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente'),
        ),
    ]
